zitadel/oidc

- pkg/op/authrequest.go
Rewrote error messages with a consistent structure to explain said errors, as well as a transition to the administrator's contact information. The administrator's information will needed to be plugged in by a more knowledgeable contributor.
Note that because I am not familiar with Go, some of the error messages may have an incorrect explanation for the error. I encourage a double check on the terminology and logic explained in my messages. If there are any errors, please correct the terminology and logic while retaining the sentence structure.
> fix(errors): improve error messages

- example/internal/mock/storage.go
- pkg/oidc/token.go
- pkg/op/client.go
- pkg/op/mock/client.mock.go
- pkg/op/mock/storage.mock.impl.go
- pkg/op/token.go
add two options:
- clock skew (add to exp, sub from iat, auth_time, nbf)
- assert userinfo (profile, email, phone, address) claims into id_token (for clients breaking the specification https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims)
> feat: add clock skew and userinfo id_token options

- pkg/oidc/introspection.go
- pkg/oidc/userinfo.go
- pkg/oidc/userinfo_test.go
AWS Cognito will return email_verified from /userinfo endpoint as string.
This fix will accept proper boolean values as well as string values.
Links for reference:
https://forums.aws.amazon.com/thread.jspa?messageID=949441&#949441
https://discuss.elastic.co/t/openid-error-after-authenticating-against-aws-cognito/206018/11
> feat: Enable parsing email_verified from string.

- pkg/oidc/keyset.go
- pkg/oidc/keyset_test.go
tested with OIDC Conformance Suite:
- https://www.certification.openid.net/plan-detail.html?plan=Cd2LNyzEZeO6I&public=true
- https://www.certification.openid.net/plan-detail.html?plan=ikPJ5gYJPs8Jn&public=true
> fix: handle keys without `use` in FindMatchingKey

- pkg/client/client.go
- pkg/client/rp/relaying_party.go
Thanks for this solid library.
On some occasions public services will expose OAuth2/OIDC endpoint on custom uri which are different from the standard patern you use in the library. I'd like to propose a new constructor to create a RelyingParty instances based on custom endpoints, different than what would be computed by the discovery method.
> feat: Allow the use of custom discovery endpoint

- pkg/client/rp/relaying_party.go
In my case here I had to have a way to know what would be the endpoint for signing out. 
I realized that the library doesn't expose this endpoint in the rp package. So what I did was add a new function in the interface and create a new field to expose the end session endpoint. 
I'm opening here this Pull request just for you all to do an analysis and see if it breaks any concepts regarding the OpenID Connect.
If it breaks anything (in the concept) please let me know why.
By the way, thank you all for maintaining this project, that is really nice.
> feat(rp): Adding end_session endpoint to relaying party interface

- README.md
Add two doc links: one for the standard Go docs and one to a relevant page relating to Zitadel.
> chore: add doc links

- pkg/oidc/token_request.go
- pkg/oidc/types.go
- pkg/oidc/types_test.go
I've added methods to `SpaceDelimitedArray` to allow it t be easily marshaled and unmarshaled via SQL.
I also added an array of the GrantTypes to help with the same.   This code is not yet in production on my side.
See https://husobee.github.io/golang/database/2015/06/12/scanner-valuer.html for a discussion of Scan/Value.
It would also be helpful to use an enumer (eg https://github.com/alvaroloes/enumer) to provide enum <-> string transformations for the various types that are defined with `iota` like `op.AccessTokenType` and `op.ApplicationType` that are required for third parties to implement some of the required interfaces.   There is positive feedback to for the idea of adding an enumer, I'm happy to do so, but I didn't want to assume that would be well received.
> feat: Add db scanner methods for SpaceDelimitedArray

- pkg/oidc/introspection.go
added `token_type`, `exp`, `iat`, `nbf`, `aud`, `iss` and `jti` (https://datatracker.ietf.org/doc/html/rfc7662#section-2.2)
required for https://github.com/zitadel/zitadel/issues/3996
> feat: add all optional claims of the introspection response

- pkg/client/client.go
- pkg/client/jwt_profile.go
- pkg/client/rp/relying_party.go
This adds a new function for `RelyingParty`s: `RefreshAccessToken`.
I didn't see any other way to do this.  Did I miss it?   It also makes the `tokenEndpointCaller` interface public so that it's more accessible.
I don't have a test for this.
> feat: add rp.RefreshAccessToken

- pkg/client/rp/relying_party.go
- pkg/oidc/token_request.go
- pkg/op/op.go
- pkg/op/storage.go
As I implemented and debugged `op.Storage`, there were a few things that I noticed that caused me to update comments.  These are those updates.
The most significant thing I noticed was that `GetKeyByIDAndUserID` is misnamed.   It should be called `GetKeyByIDAndClientID` instead.    Please add that to whatever list is kept for breaking changes that are waiting for the next major release.
> chore: adjustments to comments for things found while implementing Storage

- pkg/op/auth_request.go
- pkg/op/verifier_jwt_profile.go
What is actually stored in `jwtProfileKeySet` is a client id.  It is not a user id. 
This change makes no functional difference, it just removes some naming technical debt.
> chore: update jwtProfileKeySet to match actual use

- pkg/client/rp/relying_party.go
I added `rp.RefreshAccessToken()`.  My addition had a bug.  `rp.RefreshAccessToken()` is now covered by my tests (proprietary at the moment)
oidc.RefreshTokenRequest cannot be used to in a request to refresh tokens
because it does not explicitly include grant_types.
> fix: rp.RefreshAccessToken did not work

- pkg/op/op.go
- pkg/op/verifier_access_token.go
For various reasons, I'm not using RS256.   While `RelyingParty` had a way to specify that other `alg`s could be used, OpenIDProivder did not.    This change adds the ability to user other crypto algorithms.
Just as an aside, why not have the default accept more algorithms?   RS384, RS512, ES256, ES384, ES512 at least.
> add access token verifier ops to openidProvider

- pkg/http/cookie.go
I have use `rp.RelyingParty` in a federated mode where each client has a different base URL.   I cannot have cookies leak from one RelyingParty to another.
To stop them leaking, I need to adjust the path that the cookies use.
> feat: Add WithPath CookieHandlerOpt

- pkg/client/rp/relying_party.go
- pkg/op/op.go
- pkg/op/signer.go
This change avoids five potential race conditions.
Lazy initializes in `RelyingParty` and `OpenIDProvider` operate without locks.  Rather than adding locks, I simply moved the initialization to when the object is created.
The  OpenIDProvider signer updates when there is new data in a channel.  It was doing its work without a lock.  For that one, I added a lock.
> fix: avoid potential race conditions

- README.md
The issuer should be http://localhost:9998 NOT the http://localhost:9998/
```bash
curl http://localhost:9998/.well-known/openid-configuration
```
```json
{
"issuer":"http://localhost:9998",
"authorization_endpoint":"http://localhost:9998/auth",
"token_endpoint":"http://localhost:9998/oauth/token",
"introspection_endpoint":"http://localhost:9998/oauth/introspect",
"userinfo_endpoint":"http://localhost:9998/userinfo",
"revocation_endpoint":"http://localhost:9998/revoke",
"end_session_endpoint":"http://localhost:9998/end_session",
"jwks_uri":"http://localhost:9998/keys",
"scopes_supported":[
"openid",
"profile",
"email",
"phone",
"address",
"offline_access"
],
"response_types_supported":[
"code",
"id_token",
"id_token token"
],
"grant_types_supported":[
"authorization_code",
"implicit", …
```
> docs(README.md): fix typos 

- pkg/oidc/discovery.go
Adds an array of auth methods so that anyone wanting to validate an auth method can do so relatively easily.
> chore: add op.AllAuthMethods

- README.md
The current uri points to a 404 page, I think that the page name change
> docs: fix zitadel doc uri in the README

- pkg/client/client.go
- pkg/client/rp/relying_party.go
The RelyingParty client did not have support for EndSession/Logout.
This adds a function to end a session.  It returns the new location.
This changes is covered by tests in a private repo.
> feat: support EndSession with RelyingParty client

- NEXT_RELEASE.md
- example/server/storage/storage.go
- pkg/client/client.go
- pkg/client/rp/relying_party.go
- pkg/op/storage.go
- pkg/op/token_revocation.go
This adds a `RevokeToken()` function to the `rp` package.
Most of the implementation is inside `client`.   It also adjusts the documentation of the `Storage.RevokeToken` to reflect that the first argument can either be a token or a token id and that the second argument, the `userID` is sometimes empty.
`op.Revoke()` will now use status code 500 for server errors.
Lastly, a new markdown file is added that lists things to adjust with the next major release.  Listing these in advance allows implementors to be compatible ahead of time.
These changes are tested by automated tests in a private repo.
> feat: add rp.RevokeToken

- .github/workflows/release.yml
- example/server/storage/storage.go
- go.mod
- go.sum
- pkg/client/rp/integration_test.go
This adds an integration test that uses an RP client to create a session with an OP server. 
It refreshes its tokens and then ends the session.
This is built on top of other open pull requests: #229 #230 #231 #237 so this will look like it's changing a lot more than it actually is until those are merged and this is rebased.
Merging this bumps code coverage from 12% to 39%
> chore: add an RP/OP integration test

- pkg/oidc/introspection.go
Adding missing getters to `IntrospectionResponse` interface for fields:
- `Scope`
- `ClientID`
- `TokenType`
- `Expiration`
- `IssuedAt`
- `NotBefore`
- `Subject`
- `Audience`
- `Issuer`
- `JWTID`
> feat: add missing IntrospectionResponse getters

- pkg/oidc/userinfo.go
- pkg/oidc/userinfo_test.go
When the Address field in userinfo is nil, an empty instance of userInfoAddress is now returned. This allows for safe chaining of Get methods. All of an empty userInfoAddress' Get methods will return empty strings.
Fixes #203
> fix: nil pointer dereference on UserInfoAddress

- NEXT_RELEASE.md
- pkg/oidc/error.go
- pkg/op/storage.go
- pkg/op/token_revocation.go
Add an additional, optional, op.Storage interface so that refresh tokens
that are not JWTs do not cause failures when they randomly, sometimes, decrypt without error
```go
// CanRefreshTokenInfo is an optional additional interface that Storage can support.
// Supporting CanRefreshTokenInfo is required to be able to revoke a refresh token that
// does not happen to also be a JWTs work properly.
type CanRefreshTokenInfo interface {
// GetRefreshTokenInfo must return oidc.ErrInvalidRefreshToken when presented
// with a token that is not a refresh token.
GetRefreshTokenInfo(ctx context.Context, clientID string, token string) (userID string, tokenID string, err error)
}
```
This will have a minor conflict with #231: both add NEXT_RELEASE.md.  This branch has the version that should be kept.
> feat: add CanRefreshTokenInfo to support non-JWT refresh tokens 

- .github/workflows/release.yml
- README.md
- example/client/service/service.go
- go.mod
- pkg/client/client.go
- pkg/client/rp/integration_test.go
- pkg/http/http.go
removed a TODO: switch to io.ReadAll and drop go1.15 support
> chore: switch from iouitil to io.ReadAll

- .github/workflows/release.yml
- README.md
> chore: add go 1.20 support

- pkg/op/storage.go
My implementation of `OPStorage` now depends upon behavior that is not currently documented.  This change simply documents that behavior.
Why would I do this?  Well, I want to pass additional information from the `/authorize` request though such that the `LoginURL` is completely different.   I do this by pulling information out of the `http.Request` before `op.Authorize` sees the request.  I add that info to the request `Context` and then use that information when handling the `GetClientByClientID` call so that I can later adjust what `LoginURL` does.   Yes, that's a bit hacky, but it's all good as long as the returned client is never cached.
> doc: document lack of client caching

- README.md
- example/server/main.go
Updates docs to run the example server.
The `example/client/app` was failing with:
```
FATA[0000] error creating provider issuer does not match 
exit status 1
```
Due to mismatch of traling slash in `ISSUER`.
> docs: update example commands

- pkg/op/client.go
- pkg/op/mock/configuration.mock.go
- pkg/op/mock/generate.go
@muhlemmer 
Here's a fix for that extra stuff in go.mod.   This also auto-install the mock generator and then cleans up go.mod for that too.
Regenerating mocks created a change.   I presume the change is legitimate but if you want, I can revert that change.
See: https://github.com/zitadel/oidc/pull/296#discussion_r1121842434
> auto install things for "go generate" and then clean up afterwards

- pkg/client/client.go
- pkg/oidc/types.go
- pkg/oidc/types_test.go
- pkg/op/device_test.go
- pkg/op/op.go
Properly register SpaceDelimitedArray for all instances
of schema.Encoder inside the oidc framework.
Closes #295
> fix: use the same schema encoder everywhere

- example/server/dynamic/op.go
- example/server/exampleop/op.go
- example/server/main.go
- pkg/client/integration_test.go
- pkg/op/device_test.go
- pkg/op/op.go
BREAKING CHANGE:
- op.NewOpenIDProvider
- op.NewDynamicOpenIDProvider
The call chain of above functions did not use the context anywhere.
This change removes the context from those fucntion arguments.
> chore: remove unused context in NewOpenIDProvider

- pkg/oidc/token.go
The Scopes field in accessTokenClaims should be a  SpaceDelimitedArray, in order to allow for correct unmarshalling.
Fixes #318
> fix: unmarshalling of scopes in access token

- pkg/oidc/token.go
- pkg/oidc/token_test.go
https://github.com/zitadel/zitadel/pull/5437 can't build, because IDTokenClaims are no longer an interface matching with UserInfo in v2 of OIDC, on this line:
https://github.com/zitadel/zitadel/blob/f5d0378335ee969021de66ca05da46af020e53ec/internal/idp/providers/oidc/session.go#L50-L52
Instead, the UserInfo must be extracted from IDTokenClaims. This PR provides a Get method to make that process easier.
> feat: GetUserinfo helper method for IDTokenClaims

- pkg/oidc/types.go
- pkg/oidc/types_test.go
When Time fields was not set in JSON, the zero value `0`, resulted in a non-zero `time.Time` in conversion. This made verifier checks against a zero (unset) time always pass:
https://github.com/zitadel/oidc/blob/5a14f8d3e443d4e6a846451924bf993fcb8dd992/pkg/oidc/verifier.go#L179
This bug was most likely introduced in #283 refactorings.
Likewise, passing an empty time to `oidc.FromTime` now results in a `0` value for the JSON.
> fix: handle the zero cases for oidc.Time

- pkg/oidc/token_request.go
JWTTokenRequest.GetIssuedAt() was returning the ExpiresAt field.
This change corrects that by returning IssuedAt instead.
This bug was introduced in #283
> fix: correct returned field for JWTTokenRequest

- internal/testutil/token.go
- pkg/client/rp/relying_party.go
- pkg/client/rp/verifier.go
- pkg/client/rp/verifier_test.go
- pkg/oidc/token_request.go
- pkg/oidc/types.go
- pkg/oidc/types_test.go
- pkg/oidc/verifier.go
- pkg/oidc/verifier_parse_test.go
- pkg/oidc/verifier_test.go
- pkg/op/auth_request.go
- pkg/op/auth_request_test.go
- pkg/op/client.go
- pkg/op/client_test.go
- pkg/op/mock/authorizer.mock.go
- pkg/op/mock/authorizer.mock.impl.go
- pkg/op/op.go
- pkg/op/session.go
- pkg/op/token_intospection.go
- pkg/op/token_jwt_profile.go
- pkg/op/token_request.go
- pkg/op/token_revocation.go
- pkg/op/userinfo.go
- pkg/op/verifier_access_token.go
- pkg/op/verifier_access_token_test.go
- pkg/op/verifier_id_token_hint.go
- pkg/op/verifier_id_token_hint_test.go
- pkg/op/verifier_jwt_profile.go
- pkg/op/verifier_jwt_profile_test.go
BREAKING CHANGE:
- The various verifier types are merged into a oidc.Verifier.
- oidc.Verfier became a struct with exported fields
- use type aliases for oidc.Verifier, this binds the correct contstructor to each verifier usecase.
Closes #314
TODO:
> feat: merge the verifier types

- pkg/oidc/token.go
- pkg/oidc/token_test.go
oidc IDTokenClaims.SetUserInfo did not set the claims map from user info.
This fix merges the claims map into the IDToken Claims map.
> fix: merge user info claims into id token claims

- pkg/oidc/introspection_test.go
- pkg/oidc/regression_assert_test.go
- pkg/oidc/token.go
- pkg/oidc/token_test.go
- pkg/oidc/userinfo_test.go
- pkg/oidc/util.go
This somewhat duplicates #349.  I hit the same problem but didn't know it had been fixed.
My fix additionally removes side effects from marshaling tokens.
> fix: do not modify userInfo when marshaling

- go.mod
- go.sum
- pkg/oidc/types.go
- pkg/oidc/types_test.go
- pkg/op/auth_request_test.go
- pkg/op/client_test.go
- pkg/op/mock/authorizer.mock.impl.go
- pkg/op/op.go
This replaces `gorilla/schema` with `zitadel/schema`, which is a fork that will be maintained by us.
Only the module's path and version are updated. There are no functional changes.
Fixes #302
> chore: replace gorilla/schema with zitadel/schema

- example/server/storage/client.go
- example/server/storage/storage.go
- pkg/op/auth_request.go
- pkg/op/client.go
Update the docs and example on glob support regarding standard deviation.
Glob pattern matching was introduced as an optional interface in #297 to provide wildcard support.
1. Fix a typo
2. Document standard deviation when using globs.
3. Add example on how to toggle the underlying client implementation based on DevMode.
Open to discussion.
Closes #308
> chore: document non-standard glob client

- example/client/device/device.go
- pkg/client/client.go
- pkg/client/rp/device.go
This change enables the caller to set URL parameters when calling the
device authorization endpoint.
Resolves #354
> feat: Allow modifying request to device authorization endpoint

- pkg/op/auth_request.go
- pkg/op/auth_request_test.go
When ParseAuthorizeRequest received an invalid URL,
for example containing a semi-colon `;`,
AuthRequestError used to panic.
This was because a typed nil was passed as a interface argument.
The nil check inside AuthRequestError always resulted in false,
allowing access through the nil pointer.
Fixes #315
> fix: resolve nil pointer panic in Authorize

- example/server/exampleop/op.go
- pkg/op/device.go
- pkg/op/device_test.go
- pkg/op/op_test.go
Device authorization used a static config for the hostname where the user is redirected.
This makes it incompatible with the rest of the framework that uses dynamic issuer.
> feat: get issuer from context for device auth

- pkg/client/rp/device.go
- pkg/oidc/token_request.go
This fixes an issue where, when using the device authorization flow, the
grant type would be set twice. Some OPs don't accept this, and fail when
polling.
With this fix the grant type is only set once, which will make some OPs
happy again.
This fix is in the main branch but is missing in the next branch.
Fixes #352
> fix: Only set GrantType once (#353)

- pkg/client/rp/relying_party.go
A tiny change to provide more detail when discovery is rejected due to an issuer mismatch.
> chore: improve error message when issuer is invalid

- pkg/oidc/authorization.go
> fix: modify ACRValues parameter type to space separated strings

- example/server/exampleop/op.go
- example/server/storage/storage.go
- pkg/client/integration_test.go
- pkg/client/rp/relying_party.go
- pkg/oidc/authorization.go
Resolves #384 
This changes example op so that an auth request with  `prompt=none` will trigger a login-required error and adds a test that uses `prompt=none` and `respone_mode=fragment`.
feature: rp now support setting the response mode.
fix: `op.AuthRequestError` now honors response mode.  It previously didn't because `oidc.AuthRequest` didn't have a `GetResponseMode()` method.  
tests: additional coverage; exampleop.SetupServer now takes extra server options.
> fix/feature:  prompt=none, response_mode=fragment

- example/server/exampleop/device.go
- pkg/op/device_test.go
- pkg/op/storage.go
BREAKING CHANGE, removes methods from DeviceAuthorizationStorage:
- GetDeviceAuthorizationByUserCode
- CompleteDeviceAuthorization
- DenyDeviceAuthorization
The methods are now moved to examples as something similar can be
userful for implementers.
Closes #371
> chore: cleanup unneeded device storage methods

- pkg/client/client_test.go
- pkg/oidc/discovery.go
- pkg/oidc/types.go
- pkg/oidc/types_test.go
This changes the use of `[]language.Tag` to `oidc.Locales` in `DiscoveryConfig`. This should be compatible with callers that use the `[]language.Tag` .
Locales now implements the `json.Unmarshaler` interface. With support for json arrays or space seperated strings. The latter because `UnmarshalText` might have been implicitly called by the json library before we added `UnmarshalJSON`.
Fixes: #406
> fix: don't error on invalid i18n tags in discovery

- pkg/client/rs/resource_server.go
- pkg/client/rs/resource_server_test.go
This PR fixes `client/rs` to not error when an issuer discovery returns no introspection endpoint.
Summary of changes:
* `newResourceServer()` will only fill `rs.tokenURL` and `rs.introspectURL` if they were not given as static endpoints using `WithStaticEndpoints()`. This allows the discovery mechanism to always respect the user-provided static endpoints and only fill them when one or the other was not statically provided. Also, given that `config.introspectURL` is optional in the OIDC Discovery spec, it is no longer enforced to be present after discovery.
* `Introspect()` will now fail if the passed `ResourceServer` does not have an `IntrospectionURL()` set. This allows for graceful errors in case issuers do not provide an introspection endpoint.
* Added unit tests covering all …
> fix(client/rs): do not error when issuer discovery has no introspection endpoint

- pkg/op/session.go
- pkg/op/storage.go
To support access to all claims in the id_token_hint (like a sessionID), this PR adds a new (optional) add-on interface to the `Storage`:
```go
// CanTerminateSessionFromRequest is an optional additional interface that may be implemented by
// implementors of Storage as an alternative to TerminateSession of the AuthStorage.
// It passes the complete parsed EndSessionRequest to the implementation, which allows access to additional data.
// It also allows to modify the uri, which will be used for redirection, (e.g. a UI where the user can consent to the logout)
type CanTerminateSessionFromRequest interface {
TerminateSessionFromRequest(ctx context.Context, endSessionRequest *EndSessionRequest) (string, error)
}
```
required for https://github.com/zitadel/zitadel/pull/6226
> feat: add CanTerminateSessionFromRequest interface

- pkg/client/rp/relying_party.go
Perhaps it would be better to delete the PKCE cookie once the code exchange has been successfully completed?
It's just a line of code but if I missed something of the big picture, feel free to close this PR.
> feat: delete PKCE cookie after code exchange

- pkg/client/integration_test.go
- pkg/client/rp/relying_party.go
- pkg/client/rp/relying_party_test.go
BREAKING CHANGE:
- rename RefreshAccessToken to RefreshToken
- RefreshToken returns *oidc.Tokens instead of *oauth2.Token
This change allows the return of the id_token in an explicit manner,
as part of the oidc.Tokens struct.
The return type is now consistent with the CodeExchange function.
When an id_token is returned, it is verified.
In case no id_token was received,
RefreshTokens will not return an error.
As per specifictation:
https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
Upon successful validation of the Refresh Token,
the response body is the Token Response of Section 3.1.3.3
except that it might not contain an id_token.
Closes #364
> feat(rp): return oidc.Tokens on token refresh

- pkg/op/signer.go
This tiny change adds a "typ":"JWT" header to the tokens created. 
Alternatively, the Storage interface could be enhanced to allow user control over JWT headers.
Resolves #434
> feat: add typ:JWT header to tokens

- .github/workflows/release.yml
- README.md
- go.mod
- go.sum
- pkg/op/auth_request.go
- pkg/op/device.go
- pkg/op/op.go
- pkg/op/token.go
- pkg/op/token_client_credentials.go
- pkg/op/token_code.go
- pkg/op/token_exchange.go
- pkg/op/token_jwt_profile.go
- pkg/op/token_refresh.go
- pkg/op/token_request.go
- pkg/op/verifier_jwt_profile.go
This changeadd opentelemetry to op, for the `oauth/token` endpoint.
> feat(op): add opentelemetry to token endpoint

- go.mod
- go.sum
- pkg/op/config.go
- pkg/op/config_test.go
- pkg/op/op.go
Due to the need in zitadel to run OIDC behind a proxy,
we need to be able to overwrite the Host from the request.
To provide that, it is now possible to start a provider that parses the standarized [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header with a fallback to the Request Host field.
```
Forwarded: by=<identifier>;for=<identifier>;host=<host>;proto=<http|https>
```
In order not to break installations that might be already running behind a proxy with the header set, a seperate constructor for the provider is added for the new usecase.
> feat: issuer from Forwarded header

- example/client/service/service.go
- example/server/storage/storage.go
- example/server/storage/storage_dynamic.go
- pkg/client/client.go
- pkg/client/rs/resource_server.go
- pkg/client/rs/resource_server_test.go
- pkg/client/tokenexchange/tokenexchange.go
- pkg/crypto/sign.go
- pkg/http/http.go
- pkg/http/marshal.go
- pkg/http/marshal_test.go
- pkg/oidc/error.go
- pkg/oidc/keyset.go
- pkg/oidc/regression_test.go
- pkg/oidc/token.go
- pkg/oidc/token_request.go
- pkg/oidc/token_test.go
- pkg/oidc/types.go
- pkg/oidc/verifier.go
- pkg/op/auth_request.go
- pkg/op/auth_request_test.go
- pkg/op/signer.go
- pkg/op/storage.go
- pkg/op/token.go
- pkg/op/token_exchange.go
I noticed a mixed use of `interface{}` and `any`. This PR replaces all occurances of `interface{}` with `any` to be consistent and improve readability.
> chore: replace `interface{}` with `any`

- pkg/op/token.go
Return state as part of the token response only for implicit flow. For code flow the state should not be returned as part of the token response.
Closes #446
> fix(op): return state in token response only for implicit flow

- example/client/api/api.go
- example/server/dynamic/login.go
- example/server/dynamic/op.go
- example/server/exampleop/device.go
- example/server/exampleop/login.go
- example/server/exampleop/op.go
- go.mod
- go.sum
- pkg/op/op.go
- pkg/op/server_http.go
- pkg/op/server_legacy.go
It seems I accidentally used a outdated version of chi (v1) while upstream is already at v5. There are no breaking changes that affect us, so only the imports needed to be updated.
> chore(deps): upgrade go-chi/chi to v5

- .github/workflows/release.yml
- .releaserc.js
- SECURITY.md
Update the releaser and SECURITY.md to match the info from the the 2.11.x branch.
> chore: v2 maintenance releases

- pkg/op/server_legacy.go
This change adds the `CanTerminateSessionFromRequest` interface to the `LegecyServer` `TerminateSession` method. The optional interface was added to the `v2` OP while `v3` was still in the making. Therefore it was missed .
Related https://github.com/zitadel/zitadel/issues/6619
> fix(op): terminate session from request in legacy server

- example/server/exampleop/op.go
- pkg/op/server_http.go
- pkg/op/server_http_routes_test.go
- pkg/op/server_legacy.go
This change splits the constructor and registration of the Legacy Server. This allows it to be extended by struct embedding.
Related https://github.com/zitadel/zitadel/issues/6619
> feat(op): allow Legacy Server extension

- pkg/op/server.go
- pkg/op/server_http.go
- pkg/op/server_http_test.go
- pkg/op/server_legacy.go
- pkg/op/token_intospection.go
As introspection is a Oauth mechanism for resource servers only, it does not make sense to get an oidc client by ID. The original OP did not do this and now we make the server behavior similar.
Tested in zitadel commit https://github.com/zitadel/zitadel/commit/ac5122d2acc3da79b2bb92e5cd5c5aeeabb22872
> fix(server): do not get client by id for introspection

- pkg/op/op.go
This is a backport of PR #484 to the v2 branch.
> feat: Allow CORS policy to be configured - Backport to v2

- pkg/op/op.go
- pkg/op/server_http.go
This allows the CORS policy to be configured or disabled on an `op.Provider` via `WithCORSOptions` or on `on.RegisterServer` via `WithServerCORSOptions`. The reason for this feature is library users may want a stricter CORS policy than the default policy currently forced by the library.
This takes care not to break backwards compatibility with any interfaces, functions, or default usage (e.g. the default policy is still applied by default).
Also, this removes the CORS middleware from the `intercept` function as every upstream use of it already had the CORS middleware applied.
> feat: Allow CORS policy to be configured

- example/server/storage/storage.go
---
I'm using the example code in my tests to setup a thin OIDC server. It works fine until I enable parallel tests, because go raises race warnings.
> fix(examples): Offer Storage with non-global client

- pkg/crypto/key.go
- pkg/crypto/key_test.go
> fix(crypto): nil pointer dereference in crypto.BytesToPrivateKey

- pkg/oidc/types.go
- pkg/oidc/types_test.go
- pkg/oidc/userinfo.go
Open system reported an issue where a generic OpenID provider might return language tags like "gb".
These tags are well-formed but unknown and Go returns an error for it.
We already ignored unknown tags is ui_locale arrays lik in AuthRequest.
This change ignores singular unknown tags, like used in the userinfo `locale` claim.
> fix(oidc): ignore unknown language tag in userinfo unmarshal

- pkg/client/rp/errors.go
- pkg/client/rp/relying_party.go
By using package-level errors, as library consumer I'm able to catch specific error without do a string compare of the error messages.
After the PR, I can use `errors.Is(err, rp.ErrRelyingPartyNotSupportRevokeCaller)` to catch the specific error.
See: https://go.dev/blog/go1.13-errors
> fix: Implement package-level error for RevokeToken

- pkg/op/server_legacy.go
This changes fixes a missing redirect check in the Legacy Server's Code Exchange handler.
> fix(op): check redirect URI in code exchange

- pkg/op/auth_request.go
- pkg/op/error.go
- pkg/op/error_test.go
- pkg/op/server_http_test.go
- pkg/op/server_legacy.go
This PR changes the way we re-throw errors. In the old solution, the Legacy Server used `NewStatusError` which forces a particular HTTP status code, even if one was already set from downstream. Instead now we us `AsStatusError`. This only sets a status code if one wasn't set already.
The `WriteError` function is also rewritten to make better distinction between error types and status codes.
Related: #291
> fix: don't force server errors in legacy server

- pkg/op/op.go
- pkg/op/op_test.go
In zitadel we require different behaviors wrt public key expiry between access tokens and ID token hints.
This change splits the two verifiers in the OP.
The default is still based on Storage and passed to both verifier fields.
Related to https://github.com/zitadel/zitadel/issues/5232
> feat(op): split the access and ID token hint key sets

- pkg/op/auth_request.go
Like https://github.com/zitadel/oidc/pull/522 for end session,
this change allows passing an expired ID token hint to the authorize endpoint.
> fix(op): allow expired id token hints in authorize

- .github/workflows/issue.yml
> chore: ignore dependabot for board PRs

- pkg/client/tokenexchange/tokenexchange.go
- pkg/oidc/error.go
- pkg/oidc/token.go
- pkg/oidc/token_request.go
This change adds fields to the token exchange and token claims types.
The `act` claim has been added to describe the actor in case of impersonation or delegation. An actor can be nested in case an obtained token is used as actor token to obtain impersonation or delegation. This allows creating a chain of actors. See [RFC 8693, section 4.1](https://www.rfc-editor.org/rfc/rfc8693#name-act-actor-claim). The `invalid_target` error has been added as per RFC requirements.
The `id_token` field has been added to the Token Exchange response  so an ID Token can be returned along with an access token. This is not specified in RFC 8693, but it allows us be consistent with OpenID responses when the scope `openid` is set, while the requested token type may remain access token.
The token exchange client …
> feat: extend token exchange response

- pkg/op/token.go
For impersonation token exchange we need to persist the actor throughout token requests, including refresh token.
This PR adds the optional TokenActorRequest interface which allows to pass such actor.
> feat(op): allow setting the actor to Token Requests

- example/client/app/app.go
- pkg/oidc/introspection.go
With impersonation we assign an actor claim to our JWT/ID Tokens. This change adds the actor claim to the introspection response to follow suit.
This PR also adds the `auth_time` and `amr` claims for consistency.
Related to https://github.com/zitadel/zitadel/issues/7210
> feat(oidc): add actor claim to introspection response

- pkg/client/client.go
- pkg/http/http.go
Hello, Azure API is returning a well formatted oauth error when we try to generate a token with client credentials grant type for example. Respecting that RFC https://www.rfc-editor.org/rfc/rfc6749#section-5.2
But this library doesn't return a proper oidc.Error in that case which is too bad. So I took inspiration from the ``CallDeviceAccessTokenEndpoint`` and I propose you this PR.
> feat: return oidc.Error in case of call token failure

- pkg/client/rp/jwks.go
Fixed to include the context in which the span was created in the request.
> fix: fetchRemoteKeys context to include in request

- example/server/exampleop/op.go
- pkg/op/auth_request.go
- pkg/op/op.go
- pkg/op/server_http_routes_test.go
- pkg/op/server_legacy.go
This change requires an additional argument to the op.RegisterLegacyServer constructor which passes the Authorize Callback Handler.
This allows implementations to use their own handler instead of the one provided by the package.
The current handler is exported for legacy behavior.
This change is not considered breaking, as RegisterLegacyServer is flagged experimental.
Related to https://github.com/zitadel/zitadel/issues/6882
> feat(op): authorize callback handler as argument in legacy server registration

- pkg/client/rp/verifier.go
- pkg/client/rp/verifier_test.go
The `Nonce` func in `IDTokenVerifier` can technically be set to `nil`. We don't want to panic by calling a `nil` func. So I've updated the `VerifyIDToken` func to skip the `nonce` claim check if the func is `nil`.
> fix: Handle case where verifier Nonce func is nil 

- pkg/client/rp/relying_party.go
The OIDC spec's definition of a refresh request does not include `client_assertion` or `client_assertion_type` as valid parameters for the refresh request. See request format here: https://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken. The document only displays `client_id`, `client_secret`, `grant_type`, `refresh_token`, and `scope` as acceptable parameters.
Therefore, I propose we add the `omitempty` tags to the `ClientAssertion` and `ClientAssertionType` fields in `RefreshTokenRequest`, so that the token refresh functionality provided by `rp.RefreshTokens` can work with identity providers that may have additional logic or different expectations when these fields are included in the refresh token request.
For example, when attempting to construct an OIDC client via …
> fix: Omit non-standard, empty fields in `RefreshTokenRequest` when performing a token refresh

- pkg/oidc/verifier.go
Changed the toJoseSignatureAlgorithms function to support not only RS256 but also ES256 and PS256 when an argument of zero length is given.
See issue #605 for the reason for selecting ES256 and PS256.
> feat: add default signature algorithm

- example/client/app/app.go
This change sets the `content-type` header to `application/json` for the response sent to the browser in the app example.
This enables pretty-printing of the userinfo json document in at least Chromium.
> fix(example): set content-type in the userinfo response

- pkg/client/client.go
- pkg/crypto/key.go
- pkg/crypto/key_test.go
- pkg/oidc/token.go
Until now `BytesToPrivateKey` was only able to handle PKCS#1 RSA keys.
This PR adds support for the PKCS#8 format including RSA, ECDSA or ED25519 private keys.
These keys are used for the signing of JWT, e.g. JWT Profile assertions.
required for https://github.com/zitadel/zitadel-tools/issues/97
> feat: support PKCS#8

- pkg/op/server.go
The library copies the request headers to response headers. With this change, it copies the redirect struct headers to the response headers.
An example of an issue that the wrong copying caused:
Most HTTP clients add the content-length header to application/x-www-form-urlencoded POST requests. Redirect responses shouldn't have a content however. For example curl fails if the response body length doesn't match the response content-length header.
Before this PRs changes:
After this PRs changes:
Found while debugging this case:
https://discord.com/channels/927474939156643850/1260630682129010774/1268174893086937099
> fix: overwrite redirect content length

- pkg/oidc/error.go
- pkg/oidc/error_test.go
This change introduces the possibility to return parent errors to clients. This is implemented by an optional flag on the `*oidc.Error`.
Currently it only support setting the parent inside JSON responses, not redirect URLs. As Go errors don't unmarshall well, only the marshaller is implemented for the moment.
Related to https://github.com/zitadel/zitadel/issues/8362
> feat(op): allow returning of parent errors to client

- pkg/op/auth_request.go
- pkg/op/auth_request_test.go
Backport of https://github.com/zitadel/oidc/pull/640
Related to https://github.com/zitadel/oidc/issues/627
> fix(op): do not redirect to unverified uri on error

- example/client/app/app.go
- pkg/crypto/hash.go
- pkg/oidc/keyset.go
This change defines the hasher used for the `at_hash` claim, when the signing key is ed25519.
There is no published spec for this yet.
There is consensus here: https://bitbucket.org/openid/connect/issues/1125/_hash-algorithm-for-eddsa-id-tokens
Currently go-jose only supports the ed25519 curve key for EdDSA, so we can safely assume sha512 here.
Related to https://github.com/zitadel/zitadel/issues/8031
> feat(crypto): hash algorithm for EdDSA

- pkg/op/error_test.go
- pkg/op/server.go
When creating a new response or new redirect, the `http.Header` maps were left unitialized. This resulted in nil pointer panics when using methods such a `Set`.
This change initializes the `http.Header` maps in the `NewResponse` and `NewRedirect` functions.
Related to https://github.com/zitadel/zitadel/issues/8031 which requires setting of response headers.
> fix(op): initialize http Headers in response objects

- example/server/exampleop/op.go
- example/server/main.go
We are planning to use Zitadel as an OpenID authentication provider for some of the Camptocamp services. Such a simple customization makes example server more convenient to create E2E tests. Using environment variables instead of command line arguments or config files for easier integration with Docker.
> feat: Define redirect uris with env variables

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/oidc/verifier.go
This PR adds a specific error to handle discovery failures. 
It allows proper error handling when the issuer URL is invalid or the configuration is missing.
Thank you.
> feat(oidc): return defined error when discovery failed

- example/server/storage/oidc.go
The intention here should be to initialize a slice with a capacity of   `len(oidcPrompt`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
> fix(example): slice init length for prompt

- README.md
- example/server/config/config.go
- example/server/config/config_test.go
- example/server/main.go
- example/server/storage/user.go
- example/server/storage/user_test.go
This change allows to load users from the json file.
That should help to create better test scenarios when using example server as fake Zitadel instance for testing. For example, having several users with different permissions or presence in the internal base (known user, unknown user, blocked user, etc).
We don't need dynamic server for testing, but I could update it to make env variables unified if needed.
This is an extended version of another pull request: https://github.com/zitadel/oidc/pull/656, which was deleted by mistake.
> feat(example): Allow configuring some parameters with env variables

- pkg/oidc/types.go
- pkg/oidc/types_test.go
This changes unmarshal of Locale so that rather than ignoring just `language.ValueError` errors, it ignores all errors. Generally speaking, a bad locale value should not prevent users from authenticating.
Resolves  https://github.com/zitadel/oidc/issues/672
> fix: ignore all unmarshal errors from locale

- pkg/oidc/token.go
- pkg/op/device.go
- pkg/op/op_test.go
- pkg/op/server_http_routes_test.go
- pkg/op/token.go
- pkg/op/token_client_credentials.go
- pkg/op/token_jwt_profile.go
This attempts to solve [Issue 660](https://github.com/zitadel/oidc/issues/660).
All the details are there. TLDR; Access Token response is not compliant with OAuth 2.0. We decided to _always_ return the `scope` property in the Access Token response to comply with [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3).
The implementation consists of getting the scope from the token request, which should be already containing only the scopes that are granted.
In my opinion, a more elegant solution would be to strictly adhere with the protocol and only return the scope if has been modified from the request. If compliant, clients could assume all scopes are given by the absence of the `scope` property in the token response, this would avoid parsing the response scope. However, …
> fix(op): add scope to access token scope

- .github/workflows/release.yml
- README.md
Add Go 1.23 to the build matrix and readme.
Some readme diff is because of the pretier formatter.
Related to https://github.com/zitadel/zitadel/issues/8906
> chore(deps): upgrade go to v1.23

- example/server/main.go
Currently web clients are only working with predefined redirect uris, changed it in a way that web clients are taking those uris from ENV settings.
> feat: add redirect URI-s ENV setting to web clients

- pkg/op/auth_request.go
- pkg/op/auth_request_test.go
This pull request addresses an issue where native clients were unable to utilize HTTPS for redirects on loopback addresses.
**Changes Made:**
- Updated the redirect validation logic to accommodate HTTPS uri's for native applications
Part of this: https://github.com/zitadel/zitadel/issues/4091
> fix: allow native applications to use https:// on loopback redirect addresses

- pkg/client/key.go
ioutil package functions where deprecated in Go 1.16. ioutil.ReadFile is the same as os.ReadFile. There was a single reference left in this package. This PR fixes that. 
fix: #713 
https://pkg.go.dev/io/ioutil
> fix: migrate deprecated io/ioutil.ReadFile to os.ReadFile

- go.mod
> chore: run 'go mod tidy'

- pkg/op/token_code.go
- pkg/op/token_request.go
- pkg/op/token_request_test.go
In #721, I implemented a change to always check the code_verifier when a code_challenge is present.
Afterward, I reviewed RFC 9700 and added additional implementation following the guidance below to mitigate PKCE downgrade attacks:
> Beyond this, to prevent PKCE downgrade attacks, the authorization server MUST ensure that if there was no code_challenge in the authorization request, a request to the token endpoint containing a code_verifier is rejected.
references:
[4.8.  PKCE Downgrade Attack - RFC9700 Best Current Practice for OAuth 2.0 Security](https://www.rfc-editor.org/rfc/rfc9700.html#name-pkce-downgrade-attack)
> fix(op): Add mitigation for PKCE Downgrade Attack

- pkg/client/integration_test.go
- pkg/client/rp/relying_party.go
- pkg/http/cookie.go
Hi :wave: firstly, thank you for this great library!
LXD is a hypervisor for system containers and VMs. It can be clustered to give a private cloud like experience.
When LXD is clustered, we have an issue wherein the authorization code flow fails if the host that receives the callback (receiver of `/oidc/callback`) is different from the host that begins the flow (receiver of `/oidc/login`; see https://github.com/canonical/lxd/issues/13644). This is because the cookie handler in the relying party has different hash and encryption keys for each cluster member. Thus, when the callback is executed, the relying party cannot decode the state or PKCE cookies and the callback fails.
As discussed in the linked issue, this can be mitigated via sticky sessions on an external load balancer. However, …
> feat: Request aware cookie handling

- pkg/client/integration_test.go
- pkg/client/rp/relying_party.go
PR https://github.com/zitadel/oidc/pull/754  has introduced the optional logout hint and UI locales to the end session request. However, while working on https://github.com/zitadel/zitadel/pull/10039 , I have noticed that the integration tests on Zitadel side call `relying_party.EndSession()` without the possibility of specifying any logout hint nor ui locales.
This PR adds these 2 parameters to `relying_party.EndSession()` function.
> feat: pass optional logout hint and ui locales to end session request

- .github/workflows/release.yml
- README.md
- go.mod
- pkg/op/auth_request.go
- pkg/op/server_legacy.go
- Add Go 1.25 to the test matrix
- Oldest supported Go version is now 1.24, as required for https://github.com/zitadel/oidc/pull/796
- Fix non-constant format string build errors
> chore(go): add support for 1.25
