zitadel/oidc

pkg/utils/crypto.go
=> fix: UserInfo with JWT access token

pkg/op/tokenrequest.go
https://tools.ietf.org/html/rfc6749#section-2.3.1:
> The client identifier is encoded using the
"application/x-www-form-urlencoded" encoding algorithm per
Appendix B, and the encoded value is used as the username; the client
password is encoded using the same algorithm and used as the
password.
=> fix: decode basic auth header components (clientID, clientSecret)

pkg/client/rs/resource_server.go, pkg/op/signer.go, pkg/op/token_intospection.go, pkg/utils/http.go
and improve signer log messages
=> fix: encoding of basic auth header values

pkg/utils/crypto.go
relates to https://github.com/caos/zitadel/issues/1588
=> fix: url safe encryption with no padding

README.md
add missing feature commit and readme update
=> feat: refresh token

pkg/client/rp/relaying_party.go
follow recommendations for code_verifier: https://datatracker.ietf.org/doc/html/rfc7636#section-4.1
=> fix: make pkce code_verifier spec compliant #125

pkg/oidc/grants/client_credentials.go, pkg/oidc/token_request.go, pkg/op/config.go, pkg/op/discovery.go, pkg/op/mock/authorizer.mock.go, pkg/op/mock/client.mock.go, pkg/op/mock/configuration.mock.go, pkg/op/mock/storage.mock.go, pkg/op/op.go, pkg/op/storage.go, pkg/op/token_client_credentials.go, pkg/op/token_request.go
This PR adds support for the client_credentials grant type following the RFC here: https://datatracker.ietf.org/doc/html/rfc6749#section-4.4
=> feat(op): implemented support for client_credentials grant

pkg/http/http.go, pkg/oidc/token.go, pkg/op/auth_request.go, pkg/op/auth_request_test.go, pkg/op/token.go
=> fix: state and auth code response encoding

pkg/op/op.go
I had some difficulty understanding how to use the op library.  I've added a comment that would have helped me.
Is my comment accurate?
=> chore: add some docs to NewOpenIDProvider()

pkg/oidc/introspection.go, pkg/oidc/userinfo.go
=> feat: get all claims

pkg/op/auth_request.go, pkg/op/token_code.go
As I was debugging my implementation of `op.Storage`, I had many bugs.   Many of these bugs were harder to figure out because the error reporting was either delayed to a later step or unclear.
There are more more things that could be improved in this regard.  This pull request just scratches the surface.
=> chore: additional errors and error improvements that catch problems earlier

NOTICE
This PR provides a NOTICE file for our users to more easily understand the copyright situation.
=> chore: add notice file to explicit state the copyright

pkg/op/token_request.go
Change op.tokenHandler to follow the same pattern as the rest of the endpoint handlers inside op: provide a standard endpoint handler that uses injected data to call an exported function.
I care because I'm not using gorilla/mux and I gave up trying to get gorilla/mux to play nicely with a prefix path when used inside nchi.
With this change, this is how I'm wrapping up the endpoint handlers.  I'm using [nchi](https://github.com/muir/nchi) instead.  The plethora of interfaces makes things a bit more complex, but it's not too bad and [nject](https://github.com/muir/nject) will filter out the transformations that aren't needed on an endpoint-by-endpoint basis.
View the change with whitespace suppressed.
```go
zitadel := nject.Sequence("zitadel",
nject.Cacheable(func() op.OpenIDProvider { …
```
=> chore: change op.tokenHandler to follow the same pattern

pkg/op/auth_request.go
Same that is done on [these lines](https://github.com/zitadel/oidc/blob/main/pkg/op/auth_request.go#L299-L301) needs to be done here as well.
=> fix: allow http schema for redirect url for native apps in dev mode

README.md
Adds the missing folder names to "Basic Overview".
=> chore(examples): fix path

README.md, example/client/app/app.go, example/server/main.go
closes https://github.com/zitadel/oidc/issues/262
=> chore(examples): improve logging and how to use

example/client/app/app.go, pkg/client/rp/integration_test.go, pkg/client/rp/relying_party.go
Implemented as suggested at https://github.com/zitadel/oidc/issues/241#issuecomment-1416060264. No agreement was reached yet.
Fixes #241
Fixes #265
=> rp: allow to set custom URL parameters

README.md
=> readme: update zitdal docs link

example/server/storage/oidc.go, example/server/storage/storage.go, go.mod, go.sum, pkg/op/context.go, pkg/op/device_test.go, pkg/op/op_test.go
This adds tests for all routes
Closes #303
=> Test all routes

pkg/oidc/regression_data/oidc.AccessTokenClaims.json, pkg/oidc/token.go
=> fix: unmarshalling of scopes in access token

README.md
- rotated features table for better rendering
- add links to specifications in feature table
- remove redundant links from the resources section
- changed "Token Exhange" feature to full yes (PR #255)
- add "Device Authorization" with full yes (PR #285)
=> chore: update features in readme

pkg/op/op.go
This change allows the customization of the `/device_authorization` endpoint.
=> feat: custom endpoint for device authorization

pkg/client/rp/verifier_test.go
Trying to reproduce the issue as reported on discord: https://discord.com/channels/927474939156643850/1096512154515013724
=> chore(rp): add a custom claims test for VerifyIDToken

example/server/storage/client.go, pkg/op/device.go, pkg/op/device_test.go, pkg/op/op_test.go
=> fix: enforce device authorization grant type

pkg/op/auth_request.go, pkg/op/auth_request_test.go
Add test cases to reproduce the original bug, and it's resolution.
closes #415
- [ x Where possible E2E tests are implemented
=> fix(op): omit empty state from code flow redirect

pkg/op/server_legacy.go
Callback URL were generated wrongly during manual testing inside zitadel.
=> fix: build callback url from server, not op

pkg/op/config.go, pkg/op/config_test.go
This change allows getting the issuer host from custom headers in the same format the the `Forwarded` header.
Closes #477
=> feat(op): issuer from custom headers

pkg/client/integration_test.go, pkg/client/rp/relying_party.go
This change adds Client Credentials grant to the Relying Party.
As specified in [RFC 6749, section 4.4](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4)
Related to https://github.com/zitadel/zitadel/pull/6999 (required for integration tests)
=> feat(rp): client credentials grant

README.md
To my understanding this was introduced with https://github.com/zitadel/oidc/pull/494 but the documentation in the readme is not updated. Not sure if this was intended. In case this was on oversight, here the PR to update the docs.
=> docs: update features client credential grant

.github/dependabot.yml
=> chore(deps): enable dependabot for the v2 branch

.github/workflows/issue.yml
automatically ad prs of non engineers to board and label community prs
=> chore: update pm board action

.github/workflows/issue.yml
=> chore: remove dependabot prs

pkg/client/rp/relying_party.go
=> fix: Set unauthorizedHandler, if not defined

.github/workflows/issue.yml
=> chore(workflow): fix action/add-to-project version

example/server/exampleop/op.go, pkg/client/rp/relying_party.go
Fixes a small number of typos in GoDoc comments.
=> docs: Fixes typos in GoDoc and comments

example/server/storage/storage.go
In the example, `storage.RefreshToken.AccessToken` was not updated when a refresh token is renewed.
> ### Definition of Ready
> 
> - [ ] I am happy with the code
> - [ ] Short description of the feature/issue is added in the pr description
> - [ ] PR is linked to the corresponding user story
> - [ ] Acceptance criteria are met
> - [ ] All open todos and follow ups are defined in a new ticket and justified
> - [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
> - [ ] No debug or dead code
> - [ ] My code has no repetitions
> - [ ] Critical parts are tested automatically
> - [ ] Where possible E2E tests are implemented
> - [ ] Documentation/examples are up-to-date
> - [ ] All non-functional requirements are met
> - [ ] Functionality of the …
=> docs(example): fixed creation of refresh token

README.md
=> chore: add limited availability notice to readme

pkg/client/rp/relying_party.go, pkg/client/rp/relying_party_test.go
Add the WithPKCEFromDiscovery option to create a relying party with PKCE enabled if it is supported when query the discovery endpoint as discussed in #506.
This only works when creating an OIDC RP which performs a discovery call. With an OAuth2-only RP, an error is returned as no discovery call is performed.
Closes #506
=> feat(rp): add WithPKCEFromDisocvery
